version: '3'
services:

  # DB
  mysql:
    container_name: mysql8

    image: mysql:8
    build:
      context: .
      dockerfile: dockerfile-db

    environment:
      # root のパスワード 長さチェック有？
      MYSQL_ROOT_PASSWORD: pass
#      TZ: Asia/Tokyo
#      MYSQL_USER: databaseuser
#      MYSQL_PASSWORD: password
#      MYSQL_DATABASE: laravel

    volumes:
      # 設定 :前後はスペース不可
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      # 最初にimageを起動したときのデータ初期化&データ投入。実行順序はファイル名アルファベット順
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      #  データ保管場所
      - ./db/data:/var/lib/mysql

    restart: always
    # extra_hosts:
    #   - localhost:127.0.0.1
    ports:
      - 3306:3306
    